/* tslint:disable */
/* eslint-disable */
/**
 * MVPs
 * API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface IAllAccessTokenResponse
 */
export interface IAllAccessTokenResponse {
    /**
     * 
     * @type {boolean}
     * @memberof IAllAccessTokenResponse
     */
    success: boolean;
}
