/* tslint:disable */
/* eslint-disable */
/**
 * MVPs
 * API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface IProfileUser
 */
export interface IProfileUser {
    /**
     * 
     * @type {string}
     * @memberof IProfileUser
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof IProfileUser
     */
    uuid: string;
    /**
     * 
     * @type {string}
     * @memberof IProfileUser
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof IProfileUser
     */
    email: string;
    /**
     * 
     * @type {Date}
     * @memberof IProfileUser
     */
    updatedAt: Date;
    /**
     * 
     * @type {Date}
     * @memberof IProfileUser
     */
    createdAt: Date;
}
