/* tslint:disable */
/* eslint-disable */
/**
 * MVPs
 * API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IUserModel } from './iuser-model';
/**
 * 
 * @export
 * @interface IProfileUserResponseDto
 */
export interface IProfileUserResponseDto {
    /**
     * 
     * @type {string}
     * @memberof IProfileUserResponseDto
     */
    title: string;
    /**
     * 
     * @type {string}
     * @memberof IProfileUserResponseDto
     */
    message: string;
    /**
     * 
     * @type {IUserModel}
     * @memberof IProfileUserResponseDto
     */
    data: IUserModel;
}
