/* tslint:disable */
/* eslint-disable */
/**
 * MVPs
 * API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IProfileUserResponse } from './iprofile-user-response';
/**
 * 
 * @export
 * @interface IProfileResponse
 */
export interface IProfileResponse {
    /**
     * 
     * @type {boolean}
     * @memberof IProfileResponse
     */
    success: boolean;
    /**
     * 
     * @type {IProfileUserResponse}
     * @memberof IProfileResponse
     */
    data: IProfileUserResponse;
}
