/* tslint:disable */
/* eslint-disable */
/**
 * MVPs
 * API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { IUserResponse } from './iuser-response';
/**
 * 
 * @export
 * @interface IRegisterResponse
 */
export interface IRegisterResponse {
    /**
     * 
     * @type {boolean}
     * @memberof IRegisterResponse
     */
    success: boolean;
    /**
     * 
     * @type {IUserResponse}
     * @memberof IRegisterResponse
     */
    data: IUserResponse;
}
