/* tslint:disable */
/* eslint-disable */
/**
 * MVPs
 * API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface IUpdateUserDto
 */
export interface IUpdateUserDto {
    /**
     * 
     * @type {string}
     * @memberof IUpdateUserDto
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof IUpdateUserDto
     */
    email?: string;
    /**
     * 
     * @type {string}
     * @memberof IUpdateUserDto
     */
    password?: string;
}
