/* tslint:disable */
/* eslint-disable */
/**
 * MVPs
 * API
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
/**
 * 
 * @export
 * @interface IUserModel
 */
export interface IUserModel {
    /**
     * 
     * @type {string}
     * @memberof IUserModel
     */
    name: string;
    /**
     * 
     * @type {string}
     * @memberof IUserModel
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof IUserModel
     */
    password: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof IUserModel
     */
    tokens: Array<string>;
}
